services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # API
      - "6334:6334"  # Web UI
    volumes:
      - ./build/qdrant/data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_ORIGIN=*
    restart: unless-stopped

volumes:
  qdrant_data: